### ISSUE TITLE
Need Help Button Changes Depending on Which Worksheet You're Working On

### ISSUE THREAD

**Issue by jcbucprc** [ucdavis/LTS-Public#33]
@smithdavedesign 

The need help button changes depending on where you're in the OLTS:

Correct:

![correct](https://user-images.githubusercontent.com/64172449/83918449-98f85580-a72d-11ea-9b0c-c6e5d64bb031.png)

Incorrect:

![incorrect](https://user-images.githubusercontent.com/64172449/83918459-9f86cd00-a72d-11ea-98b2-24cd5b58c169.png)

Should be the same across the OLTS.

**Comment by smithdavedesign** [comment]
Thanks for pointing that out. Fixed
